steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'usgcr.io/$PROJECT_ID/anthos-front-end', '.']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'anthos-front-end', '--image', 'us.gcr.io/$PROJECT_ID/anthos-front-end', '--region', 'us-central1', '--allow-unauthenticated', '--timeout','50m', '--no-cpu-throttling', '--memory', '2Gi', '--cpu', '4', '--update-env-vars', 'REACT_APP_BACKEND="https://localhost']
images: ['us.gcr.io/$PROJECT_ID/anthos-front-end']

